- hosts: dizp
  gather_facts: no
  tasks:
  - raw: apt-get install -y --force-yes -o "Acquire::http::Timeout=10" --no-upgrade python-apt 
  tags: 
  - initial
  - install

- hosts: dizp
  roles:
  - { role: common/admins, users: ['tbo',] }
  - common/linux-server
  - common/ntp

- hosts: tbo-services
  roles:
    - ns-authoritative
    - origin
    - controller

- hosts: tbo-rr
  roles:
    - reqnrouter
    - frontend