- hosts: ctrgn
  gather_facts: no
  tasks:
  - raw: apt-get install -y --force-yes -o "Acquire::http::Timeout=10" --no-upgrade python-apt 
  tags: 
  - initial
  - install

- hosts: ctrgn
  roles:
  - { role: common/admins, users: ['tbo',] }
  - common/linux-server
  - common/ntp
