
- name: install nginx
  package:
    name: nginx
    state: present

- name: Create directory /var/www
  file:
    path: /var/www
    state: directory
    owner: www-data
    group: www-data

- name: remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: create config file for load balancer
  template:
    src: lb.conf
    dest: /etc/nginx/sites-available/lb.conf
  notify: reload nginx

- name: "Create symlink to the sites-enabled"
  file:
    dest: /etc/nginx/sites-enabled/lb.conf
    src: /etc/nginx/sites-available/lb.conf
    state: link
  notify: reload nginx
